Loan Approval Classification Project

OBJECTIVE

The objective of this project is to develop different classification models using various machine learning algorithms and compare their performance on the loan data set. Different classification models, including Logistic Regression, KNN, SVM, Random Forest, etc., are developed for the loan data set.

In [1]:
import pandas as pd
df=pd.read_csv("loan_data.csv")
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [2]:
df.shape

(45000, 14)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object
 2   person_education                45000 non-null  object
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  object
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  object
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 4.8+ MB

In [4]:
df.describe()

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,loan_status
count,45000.000000,4.500000e+04,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000
mean,27.764178,8.031905e+04,5.410333,9583.157556,11.006606,0.139725,5.867489,632.608756,0.222222
std,6.045108,8.042250e+04,6.063532,6314.886691,2.978808,0.087212,3.879702,50.435865,0.415744
min,20.000000,8.000000e+03,0.000000,500.000000,5.420000,0.000000,2.000000,390.000000,0.000000
25%,24.000000,4.720400e+04,1.000000,5000.000000,8.590000,0.070000,3.000000,601.000000,0.000000
50%,26.000000,6.704800e+04,4.000000,8000.000000,11.010000,0.120000,4.000000,640.000000,0.000000
75%,30.000000,9.578925e+04,8.000000,12237.250000,12.990000,0.190000,8.000000,670.000000,0.000000
max,144.000000,7.200766e+06,125.000000,35000.000000,20.000000,0.660000,30.000000,850.000000,1.000000

In [5]:
df.duplicated().sum()

0

In [6]:
df.isnull().sum()

person_age                        0
person_gender                     0
person_education                  0
person_income                     0
person_emp_exp                    0
person_home_ownership             0
loan_amnt                         0
loan_intent                       0
loan_int_rate                     0
loan_percent_income               0
cb_person_cred_hist_length        0
credit_score                      0
previous_loan_defaults_on_file    0
loan_status                       0
dtype: int64

In [7]:
df["loan_status"].value_counts()

loan_status
0    35000
1    10000
Name: count, dtype: int64

In [8]:
df.columns

Index(['person_age', 'person_gender', 'person_education', 'person_income',
       'person_emp_exp', 'person_home_ownership', 'loan_amnt', 'loan_intent',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length',
       'credit_score', 'previous_loan_defaults_on_file', 'loan_status'],
      dtype='object')

In [9]:
columns = ['person_age',  'person_income','person_emp_exp',  'loan_amnt', 
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length',
       'credit_score', ]

for col in columns:
    Q1=df[col].quantile(0.25)
    Q3=df[col].quantile(0.75)
    IQR=Q3-Q1
    LOWER_BOUND = Q1-1.5*IQR
    UPPER_BOUND = Q3+1.5*IQR
    outliers = df[(df[col]< LOWER_BOUND) | (df[col] > UPPER_BOUND)]
    print(outliers.shape[0])

2188
2218
1724
2348
124
744
1366
467

In [10]:
columns = ['person_age',  'person_income','person_emp_exp',  'loan_amnt', 
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length',
       'credit_score', ]

for col in columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df[col] = df[col].clip(lower=lower_bound, upper=upper_bound)

In [11]:
columns = ['person_age',  'person_income','person_emp_exp',  'loan_amnt', 
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length',
       'credit_score', ]

for col in columns:
    Q1=df[col].quantile(0.25)
    Q3=df[col].quantile(0.75)
    IQR=Q3-Q1
    LOWER_BOUND = Q1-1.5*IQR
    UPPER_BOUND = Q3+1.5*IQR
    outliers = df[(df[col]< LOWER_BOUND) | (df[col] > UPPER_BOUND)]
    print(outliers.shape[0])

0
0
0
0
0
0
0
0

In [12]:
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    print(f"\nColumn: {col}")
    print(f"Number of Unique Values: {df[col].nunique()}")

Column: person_gender
Number of Unique Values: 2

Column: person_education
Number of Unique Values: 5

Column: person_home_ownership
Number of Unique Values: 4

Column: loan_intent
Number of Unique Values: 6

Column: previous_loan_defaults_on_file
Number of Unique Values: 2

In [13]:
df = pd.get_dummies(df, columns=['person_gender','person_education',
'person_home_ownership','loan_intent','previous_loan_defaults_on_file'], 
drop_first=True)

The dataset was cleaned and preprocessed for modeling. Categorical variables such as gender, education, home ownership, loan intent, and loan default history were transformed into numerical form using One-Hot Encoding. This transformation enables the machine learning algorithm to understand the categorical data properly.

In [14]:
X = df.drop('loan_status', axis=1)
y = df['loan_status']

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42,
    stratify=y)

In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(36000, 22)
(9000, 22)
(36000,)
(9000,)

## Logestic Regressor

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

In [19]:
y_pred_log = log_model.predict(X_test_scaled)
print("Logistic Regression Accuracy:", accuracy_score(y_test,y_pred_log))

Logistic Regression Accuracy: 0.9007777777777778

## KNN Classifier

In [20]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [21]:
y_pred_knn = knn_model.predict(X_test_scaled)
print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))

KNN Accuracy: 0.895

## SVM Classifier

In [22]:
from sklearn.svm import SVC

svm_model = SVC(kernel='rbf')
svm_model.fit(X_train_scaled, y_train)

SVC()

In [29]:
y_pred_svm = svm_model.predict(X_test_scaled)
print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))

SVM Accuracy: 0.9168888888888889

## Random Forest Classifier

In [24]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=250,random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=250, random_state=42)

In [25]:
y_pred_rf = rf_model.predict(X_test)
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))

Random Forest Accuracy: 0.9283333333333333

In [43]:
rf = RandomForestClassifier(random_state=42)
param_grid = {'n_estimators': [100,200,300,400],'max_depth': [20, 30, None],
    'min_samples_split': [2, 5],'min_samples_leaf': [1, 2],
    'max_features': ['sqrt', 'log2',0.6,0.8],'class_weight': [None, 'balanced']}
grid = GridSearchCV(estimator=rf,param_grid=param_grid,cv=3,scoring='accuracy',
    n_jobs=-1,verbose=2)
grid.fit(X_train, y_train)

Fitting 3 folds for each of 384 candidates, totalling 1152 fits

GridSearchCV(cv=3, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'class_weight': [None, 'balanced'],
                         'max_depth': [20, 30, None],
                         'max_features': ['sqrt', 'log2', 0.6, 0.8],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [100, 200, 300, 400]},
             scoring='accuracy', verbose=2)

In [47]:
best_rf = grid.best_estimator_
y_pred = best_rf.predict(X_test)

In [48]:
print("Best Parameters:", grid.best_params_)
print(f"Tuned Accuracy: {accuracy_score(y_test, y_pred)*100:.2f}%")

Best Parameters: {'class_weight': None, 'max_depth': 30, 'max_features': 0.6, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 200}
Tuned Accuracy: 93.37%

Out of all the models, the highest accuracy score was achieved by the Random Forest model, signifying its ability to effectively handle complex patterns in the loan approval data set. The performance of the Random Forest model is better in comparison to the Logistic Regression, SVM, and KNN models in classifying the data and predicting the outcome of the loan approval process.